// Generated by https://quicktype.io

export interface MoviesDBTrending {
  page: number
  results: Movie[]
  total_pages: number
  total_results: number
}

export interface Movie {
  genre_ids: number[]
  original_language: OriginalLanguage
  original_title?: string
  poster_path: string
  video?: boolean
  title?: string
  vote_count: number
  overview: string
  release_date?: string
  vote_average: number
  id: number
  adult?: boolean
  backdrop_path: string
  popularity: number
  media_type: MediaType
  first_air_date?: string
  name?: string
  original_name?: string
  origin_country?: string[]
}

export enum MediaType {
  Movie = "movie",
  Tv = "tv"
}

export enum OriginalLanguage {
  En = "en",
  Es = "es"
}
